/**
 * Hand-drawn 16×16 pixel icons. Each character is one pixel; '.' is transparent.
 * Rendered to a single SVG <path> per colour by `pixelSvg()`.
 */
export const PALETTE: Record<string, string> = {
  k: '#0b0708',
  w: '#f6f0e8',
  g: '#a59a9b',
  G: '#5a4c4e',
  r: '#e01b1b',
  R: '#7a0000',
  y: '#ffcf33',
  Y: '#b8860b',
  o: '#ff8a1f',
  b: '#3a78f0',
  B: '#1b3d8f',
  c: '#76d6ff',
  n: '#3dff6e',
  N: '#16a83b',
  p: '#ff7ad9',
  s: '#c98b5e',
};

export const ICONS = {
  notepad: [
    '................',
    '..kkkkkkkkkk....',
    '..kwwwwwwwwkk...',
    '..kwGGGGGGwkwk..',
    '..kwwwwwwwwkkkk.',
    '..kwGGGGGGGGGwk.',
    '..kwwwwwwwwwwwk.',
    '..kwGGGGGGGGwwk.',
    '..kwwwwwwwwwwwk.',
    '..kwGGGGGGGGGwk.',
    '..kwwwwwwwwwwwk.',
    '..kwGGGGGwwwwwk.',
    '..kwwwwwwwwrwwk.',
    '..kwwwwwwwrrrwk.',
    '..kkkkkkkkkkkkk.',
    '................',
  ],
  floppy: [
    '................',
    '.kkkkkkkkkkkkk..',
    '.kRRkggggggkRRk.',
    '.kRRkggggGgkRRk.',
    '.kRRkggggGgkRRk.',
    '.kRRkggggggkRRk.',
    '.kRRRRRRRRRRRRk.',
    '.kRRRRRRRRRRRRk.',
    '.kRRwwwwwwwwRRk.',
    '.kRRwrrrrrrwRRk.',
    '.kRRwwwwwwwwRRk.',
    '.kRRwGGGGGGwRRk.',
    '.kRRwwwwwwwwRRk.',
    '.kRRwGGGGwwwRRk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  frame: [
    '................',
    '.YYYYYYYYYYYYYY.',
    '.YyyyyyyyyyyyyY.',
    '.YycccccccooyyY.',
    '.YyccccccooooyY.',
    '.YycccccccooyyY.',
    '.YyccccccccccyY.',
    '.YyccccGcccccyY.',
    '.YycccGGGccccyY.',
    '.YyccGGGGGcGcyY.',
    '.YycGGGGGGGGGyY.',
    '.YyNNNNNNNNNNyY.',
    '.YyNNNNNNNNNNyY.',
    '.YyyyyyyyyyyyyY.',
    '.YYYYYYYYYYYYYY.',
    '................',
  ],
  vhs: [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGk.',
    '.kGwwwwwwwwwwGk.',
    '.kGwrrrrrrrrwGk.',
    '.kGwwwwwwwwwwGk.',
    '.kGGGGGGGGGGGGk.',
    '.kGkkkGGGGkkkGk.',
    '.kGkwkGGGGkwkGk.',
    '.kGkkkGGGGkkkGk.',
    '.kGGGGGGGGGGGGk.',
    '.kGGGkkkkkkGGGk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  terminal: [
    '................',
    '.GGGGGGGGGGGGGG.',
    '.GrGyGnGGGGGGGG.',
    '.GkkkkkkkkkkkkG.',
    '.GknkkkkkkkkkkG.',
    '.GkknkkkkkkkkkG.',
    '.GkkknkkkkkkkkG.',
    '.GkknkkkkkkkkkG.',
    '.GknkknnnnkkkkG.',
    '.GkkkkkkkkkkkkG.',
    '.GkkkkkkkkkkkkG.',
    '.GkkkkkkkkkkkkG.',
    '.GkkkkkkkkkkkkG.',
    '.GGGGGGGGGGGGGG.',
    '................',
    '................',
  ],
  code: [
    '................',
    '..BBBBBBBBBBB...',
    '..BbbbbbbbbbBB..',
    '..BbbbbbbbbbBbB.',
    '..BbbbbbbbbbBBBB',
    '..BbbbbbbbbbbbbB',
    '..BbbbbbbbbbbbbB',
    '..BbbbbbbbbbbbbB',
    '..BbwwwwbbwwwwbB',
    '..BbbwwbbwwbbbbB',
    '..BbbwwbbbwwwbbB',
    '..BbbwwbbbbbwwbB',
    '..BbbwwbbwwwwbbB',
    '..BbbbbbbbbbbbbB',
    '..BBBBBBBBBBBBBB',
    '................',
  ],
  mail: [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwwk.',
    '.kGwwwwwwwwwwGk.',
    '.kwGwwwwwwwwGwk.',
    '.kwwGwwwwwwGwwk.',
    '.kwwwGwwwwGwwwk.',
    '.kwwwwGrrGwwwwk.',
    '.kwwwwwrrwwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  trash: [
    '................',
    '......kkkk......',
    '......k..k......',
    '..kkkkkkkkkkkk..',
    '..kggggggggggk..',
    '..kkkkkkkkkkkk..',
    '...kgGgGgGgGk...',
    '...kgGgGgGgGk...',
    '...kgGgGgGgGk...',
    '...kgGgGgGgGk...',
    '...kgGgGgGgGk...',
    '...kgGgGgGgGk...',
    '...kgGgGgGgGk...',
    '...kgGgGgGgGk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  button: [
    '................',
    '................',
    '................',
    '................',
    '.....rrrrrr.....',
    '...rrwwrrrrrr...',
    '..rrwrrrrrrrrr..',
    '..rrrrrrrrrrrr..',
    '..RrrrrrrrrrrR..',
    '..GRRRRRRRRRRG..',
    '..GGRRRRRRRRGG..',
    '.GGGGGGGGGGGGGG.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  gear: [
    '................',
    '......gggg......',
    '..gg..gggg..gg..',
    '..gggggggggggg..',
    '...gggggggggg...',
    '...gggGkkGggg...',
    '.gggggkkkkggggg.',
    '.ggggkkkkkkgggg.',
    '.ggggkkkkkkgggg.',
    '.gggggkkkkggggg.',
    '...gggGkkGggg...',
    '...gggggggggg...',
    '..gggggggggggg..',
    '..gg..gggg..gg..',
    '......gggg......',
    '................',
  ],
  film: [
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kwwkkwwkkwwkkk.',
    '.kkwwkkwwkkwwkk.',
    '.kkkkkkkkkkkkkk.',
    '.kGGGGGGGGGGGGk.',
    '.kGwwwwGGGGGGGk.',
    '.kGGGGGGGGGGGGk.',
    '.kGwwwwwwwGGGGk.',
    '.kGGGGGGGGGGGGk.',
    '.kGwwwGGGGGGGGk.',
    '.kGGGGGGGGGGGGk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  smiley: [
    '................',
    '................',
    '...nnn....nnn...',
    '..nnnnn..nnnnn..',
    '..nnNnn..nnNnn..',
    '..nnnnn..nnnnn..',
    '...nnn....nnn...',
    '................',
    '................',
    '................',
    '...n........n...',
    '....n......n....',
    '.....nnnnnn.....',
    '................',
    '................',
    '................',
  ],
  glove: [
    '................',
    '....rrrrrr......',
    '...rrrrrrrrr....',
    '..rrwrrrrrrrr...',
    '..rwrrrrrrrrrr..',
    '..rrrrrrrrrrrr..',
    '..rrrrrrrrrrrrR.',
    '..rrrrrrrrrrrrR.',
    '...rrrrrrrrrrR..',
    '...RrrrrrrrrRR..',
    '....RRRRRRRR....',
    '....wwwwwwww....',
    '....wGwGwGww....',
    '....wwwwwwww....',
    '....kkkkkkkk....',
    '................',
  ],
  tie: [
    '................',
    '.....kkkkkk.....',
    '.....kwwwwk.....',
    '......kbbk......',
    '......bbbb......',
    '......bbBb......',
    '.....bbbBbb.....',
    '.....bbBbbb.....',
    '.....bBbbbb.....',
    '.....bbbbBb.....',
    '.....bbbBbb.....',
    '.....bbBbbb.....',
    '......bbbb......',
    '.......bb.......',
    '................',
    '................',
  ],
  folder: [
    '................',
    '................',
    '.YYYYY..........',
    '.YyyyyY.........',
    '.YyyyyyYYYYYYYY.',
    '.YyyyyyyyyyyyyY.',
    '.YYYYYYYYYYYYYY.',
    '.YyyyyyyyyyyyyY.',
    '.YyyyyyyyyyyyyY.',
    '.YyyyyyyyyyyyyY.',
    '.YyyyyyyyyyyyyY.',
    '.YyyyyyyyyyyyyY.',
    '.YyyyyyyyyyyyyY.',
    '.YYYYYYYYYYYYYY.',
    '................',
    '................',
  ],
  warning: [
    '................',
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kyyyyk.....',
    '.....kykkyk.....',
    '....kyykkyyk....',
    '....kyykkyyk....',
    '...kyyykkyyyk...',
    '...kyyykkyyyk...',
    '..kyyyyyyyyyyk..',
    '..kyyyykkyyyyk..',
    '.kyyyyykkyyyyyk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  speaker: [
    '................',
    '................',
    '................',
    '.......k........',
    '......kk....w...',
    '.....kgk..w..w..',
    '.kkkkggk...w..w.',
    '.kgggggk...w..w.',
    '.kgggggk...w..w.',
    '.kkkkggk...w..w.',
    '.....kgk..w..w..',
    '......kk....w...',
    '.......k........',
    '................',
    '................',
    '................',
  ],
} satisfies Record<string, string[]>;

export type IconName = keyof typeof ICONS;

const cache = new Map<string, string>();

/** Turns a pixel map into a compact SVG string (one path per colour, row runs merged). */
export function pixelSvg(name: IconName): string {
  const hit = cache.get(name);
  if (hit) return hit;

  const rows = ICONS[name];
  const paths = new Map<string, string[]>();
  rows.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      if (ch === '.' || !PALETTE[ch]) {
        x++;
        continue;
      }
      let run = 1;
      while (row[x + run] === ch) run++;
      const list = paths.get(ch) ?? [];
      list.push(`M${x} ${y}h${run}v1h-${run}z`);
      paths.set(ch, list);
      x += run;
    }
  });

  const body = [...paths.entries()]
    .map(([ch, d]) => `<path fill="${PALETTE[ch]}" d="${d.join('')}"/>`)
    .join('');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">${body}</svg>`;
  cache.set(name, svg);
  return svg;
}

export function pixelDataUri(name: IconName): string {
  return `data:image/svg+xml;utf8,${encodeURIComponent(pixelSvg(name))}`;
}
